# Generated by Django 2.0.2 on 2018-03-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIdistricting_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='convex_hull_ratio',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='length_width',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='polsby_popper',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='reock',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='shwartzberg',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
    ]
