# Generated by Django 2.0.2 on 2018-03-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIdistricting_App', '0002_auto_20180313_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='id',
        ),
        migrations.AlterField(
            model_name='district',
            name='district_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
