# Generated by Django 2.0.2 on 2018-03-13 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WIdistricting_App', '0003_auto_20180313_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='District_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='district_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WIdistricting_App.District_Plan'),
        ),
    ]
