# Generated by Django 2.0.2 on 2018-03-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIdistricting_App', '0004_auto_20180313_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='district_plan',
            name='time_stamp',
            field=models.DateField(auto_now=True),
        ),
    ]
