# Generated by Django 2.0.2 on 2018-03-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIdistricting_App', '0005_district_plan_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='district_plan',
            name='avg_convex_hull',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district_plan',
            name='avg_length_width',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district_plan',
            name='avg_polsby_popper',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district_plan',
            name='avg_reock',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district_plan',
            name='avg_schwartzberg',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district_plan',
            name='competitiveness',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district_plan',
            name='district_split_count',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district_plan',
            name='efficiency_gap',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district_plan',
            name='mean_median_diff',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district_plan',
            name='partisan_bias',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district_plan',
            name='rep_fairness',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district_plan',
            name='split_county_count',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district_plan',
            name='split_municipal_count',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='district_plan',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
