# Generated by Django 2.0.2 on 2018-03-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIdistricting_App', '0006_auto_20180313_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='district_plan',
            name='equal_population',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='district_plan',
            name='map_id',
            field=models.IntegerField(null=True),
        ),
    ]
