# Generated by Django 2.0.3 on 2018-04-08 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WIdistricting_App', '0011_auto_20180408_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pre_district',
            old_name='total_votes',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='pre_district',
            name='blue_votes',
        ),
        migrations.RemoveField(
            model_name='pre_district',
            name='red_votes',
        ),
    ]
