# Generated by Django 2.0.3 on 2018-04-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIdistricting_App', '0012_auto_20180408_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_district',
            name='votes',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
