# Generated by Django 2.0.2 on 2018-04-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIdistricting_App', '0013_auto_20180408_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_district',
            name='district_no',
            field=models.IntegerField(null=True),
        ),
    ]
