# Generated by Django 2.0.2 on 2018-04-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIdistricting_App', '0015_auto_20180409_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_district',
            name='district_no',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
