# Generated by Django 2.0.2 on 2018-04-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIdistricting_App', '0017_auto_20180409_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='district_no',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='office',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
