# Generated by Django 2.0.2 on 2018-04-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WIdistricting_App', '0018_auto_20180415_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='district_plan',
        ),
    ]
