# Generated by Django 2.0.2 on 2018-04-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIdistricting_App', '0019_remove_district_district_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district_plan',
            name='equal_population',
            field=models.IntegerField(null=True),
        ),
    ]
